services:
  # ##< API Gateway Service
  - type: web
    runtime: docker
    name: fota-api-gateway
    repo: https://github.com/Yebei-Gideon/Secure-IoT-Firmware-Over-The-Air-Platform
    rootDir: .
    healthCheckPath: /health
    plan: free
    branch: main
    buildFilter:
      paths:
        - apps/api-gateway/**/*
        - packages/**/*
    envVars:
      - key: API_NAME
        sync: false
      - key: API_DESCRIPTION
        sync: false
      - key: API_VERSION
        sync: false
      - key: API_URL
        sync: false
      - key: PORT
        sync: false
      - key: API_PREFIX
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SHADOW_DATABASE_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
